FROM node:12

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/jponcy/fake-game-api.git && \
    npm install --production

EXPOSE 3000

## La commande de la documentation donne un soucis avec la gestion des ports.
ENTRYPOINT npm run start:separed
